### ISSUE TITLE
[request] lift bed before moving

### ISSUE THREAD

**Issue by TylonHH** [Peaches491/OctoPrint-Touchtest#4]
Hi,
it's not good for the bed when you move your nozzle over an homed bed. You could destroy or scratch your bed.
So before you move you should ``G1 Z10 F###`` press a button to move the nozzle, then ``G28 Z``. That would be perfect!

**Comment by paulr4** [comment]
I second this!
My first thought: Yay, great idea! Second thought: Oh, sadly unusable. :(

**Comment by poorredneck** [comment]
Third this! I'm currently using custom control editor to do this as this is exactly what happened to me. Big scratch right across my glass. 
Each button press should raise Z by 5mm, move to specified location, then drop back down.
A better solution too would be to set a custom Z height for the target. Some of us level the bed with feeler gauges instead of the paper method. I use a 0.20mm feeler gauge so having a configurable Z height to set would be awesome.

**Comment by TylonHH** [comment]
Just for clearance. When I use my feeler gauge 0,1 the printer thinks he is on Z 0.
But it's just a configuration thing.

**Comment by poorredneck** [comment]
I personally do not do an "extra height". If Z is at 0.20 my nozzle is at
0.20 no extra space. My first layers are perfect.

**Comment by Mavyre** [comment]
:+1:
Actually, it's very simple to do. I forked it and I'll try it the next few days.

**Comment by luizmotta** [comment]
Hi all, just to let you know that this plugin is being maintained again and this feature has been implemented in the latest version. Please update.
